# Generated by Django 4.0.3 on 2022-03-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the dish', max_length=1000),
        ),
    ]
