# Generated by Django 4.0.3 on 2022-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_dish_cooking_time_alter_dish_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooking_time',
            field=models.TimeField(null=True),
        ),
    ]
