# Generated by Django 4.0.3 on 2022-03-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
