# Generated by Django 4.0.3 on 2022-03-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_dish_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
