# Generated by Django 3.2.12 on 2022-03-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dish'),
        ),
    ]
