# Generated by Django 4.0.3 on 2022-03-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
